annotation error message writting 2

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -25,8 +25,8 @@ jobs:
           file_size=$(stat -c%s "coding-style-reports.log")
           if [ $file_size -gt 0 ]; then
             file_content=$(cat coding-style-reports.log)
-            echo "::error::Contenu du fichier : $file_content"
-            exit 84
+            echo "::error::$file_content"
+#            exit 84
           fi
            
   check_program_compilation:
